### ISSUE TITLE
how to run over polarcode?

### ISSUE THREAD

**Issue by liaocs2008** [facebookresearch/HyperNetworkDecoder#3]
Hi,

It seems that this implementation always takes a generator matrix for encoding. But this is not applicable to general polar code belief propagation. For example, you have to calculate those free  positions and put message there. This is not by multiplication with generator matrix. 

As a result, may I ask how to run over polar code?

**Comment by enk100** [comment]
In polar code you have completely different trellis graph. So you need to change the graph code.
